export const locales = ["es", "pt", "en"] as const;
export type Locale = (typeof locales)[number];

const es = {
  nav: { courses: "Cursos", method: "Método", about: "Nosotros", members: "Área de estudiantes", cta: "Quiero aprender", menu: "Abrir menú", close: "Cerrar menú" },
  hero: { eyebrow: "Español para conectar de verdad", titleA: "Habla español.", titleB: "Abre tu mundo.", text: "Clases online con profesores colombianos para brasileños y estadounidenses que quieren conversar con naturalidad, no solo memorizar reglas.", primary: "Quiero empezar", secondary: "Conoce el método", note: "Lista de espera · Sin compromiso", card: "Tu próxima conversación", phrase: "¡Qué gusto conocerte!", translation: "Prazer em conhecer você! · Nice to meet you!", live: "Práctica en vivo", culture: "Cultura colombiana", confidence: "Confianza al hablar" },
  benefits: { eyebrow: "Mucho más que vocabulario", title: "Aprende un idioma. Vive la conexión.", text: "Cada experiencia está pensada para llevar el español del aula a tu vida.", items: [
    ["Conversación práctica", "Habla desde la primera clase con situaciones que realmente vas a vivir."],
    ["Cultura que se siente", "Descubre expresiones, historias y costumbres de Colombia y Latinoamérica."],
    ["Aprendizaje flexible", "Combina clases en vivo, lecciones grabadas y práctica a tu ritmo."],
    ["Guía personal", "Recibe acompañamiento cercano de profesores que conocen tu camino."],
  ]},
  how: { eyebrow: "Tu camino, paso a paso", title: "Así funciona Habla", steps: [
    ["01", "Descubrimos tu punto de partida", "Cuéntanos tus objetivos y encuentra la ruta ideal para tu nivel y rutina."],
    ["02", "Aprendes haciendo", "Practica con clases dinámicas, retos cortos y conversaciones reales."],
    ["03", "Conectas con confianza", "Usa tu español para viajar, trabajar y crear nuevos vínculos."],
  ]},
  courses: { eyebrow: "Explora tu próxima etapa", title: "Cursos para español de la vida real", text: "Una muestra de las experiencias que estamos preparando.", sample: "Contenido de muestra", level: "Nivel", format: "Formato", duration: "Duración", outcome: "Al finalizar podrás", cards: [
    ["Primeras palabras", "A1 · Principiante", "En vivo + grabado", "8 semanas", "Presentarte, pedir información y resolver situaciones cotidianas."],
    ["Conversaciones con ritmo", "A2–B1 · Intermedio", "Grupos pequeños", "10 semanas", "Mantener conversaciones espontáneas con más seguridad."],
    ["Español profesional", "B1–B2 · Avanzando", "Taller en vivo", "6 semanas", "Comunicar ideas con claridad en reuniones y contextos de trabajo."],
  ], cta: "Ver detalles" },
  founders: { eyebrow: "Tus profes, tu equipo", title: "Hola, somos Natalia y José", text1: "Somos profesores colombianos y creemos que un idioma se aprende cuando deja de sentirse como una prueba y empieza a sentirse como una conversación.", text2: "Creamos Habla para acompañar a estudiantes de Brasil y Estados Unidos con una enseñanza cercana, práctica y llena de cultura.", quote: "Queremos que cada palabra nueva te acerque a una persona, un lugar o una posibilidad.", natalia: "Natalia", nataliaRole: "Cofundadora · Profesora", jose: "José", joseRole: "Cofundador · Profesor", placeholder: "Espacio para foto oficial" },
  testimonials: { eyebrow: "Historias que pronto hablarán", title: "La comunidad está empezando", text: "Estos espacios muestran cómo se presentarán las experiencias reales de estudiantes después del lanzamiento.", placeholder: "TESTIMONIO DE MUESTRA — NO ES UNA RESEÑA REAL", quotes: [
    "Aquí compartiremos cómo una estudiante brasileña ganó confianza para conversar durante sus viajes.",
    "Aquí mostraremos el progreso de un profesional en Estados Unidos usando español en el trabajo.",
    "Aquí destacaremos una historia real sobre aprender en comunidad y conectar con la cultura.",
  ], student: "Nombre de estudiante", detail: "País · Curso" },
  final: { eyebrow: "Tu español empieza con una conversación", title: "¿Listo para decir mucho más que hola?", text: "Únete a la lista y sé de las primeras personas en conocer nuestros cursos, fechas y beneficios de lanzamiento.", cta: "Quiero unirme", note: "Te escribiremos solo con novedades importantes." },
  footer: { text: "Español práctico, cultura viva y conexión humana.", explore: "Explora", contact: "Contacto", social: "Síguenos", email: "hola@habla.example", instagram: "Instagram (próximamente)", youtube: "YouTube (próximamente)", privacy: "Privacidad", terms: "Términos", rights: "© 2026 Habla. Todos los derechos reservados.", language: "Idioma" },
  login: { title: "Qué gusto verte", text: "Continúa tu camino en español.", email: "Correo electrónico", password: "Contraseña", forgot: "¿Olvidaste tu contraseña?", submit: "Entrar a mi espacio", demo: "Prototipo visual: usa cualquier correo y contraseña.", back: "Volver al inicio", noAccount: "¿Aún no tienes acceso?", join: "Únete a la lista" },
  members: { eyebrow: "Mi espacio", hello: "¡Hola, Camila!", text: "Tu próxima conversación está más cerca.", progress: "Progreso del curso", complete: "completado", continue: "Continuar lección", lessons: "Lecciones grabadas", materials: "Materiales", upcoming: "Próximas actividades", announcements: "Avisos de tus profes", viewAll: "Ver todo", download: "Descargar", mock: "Vista de demostración · Datos de muestra", lessonName: "Pedir y dar indicaciones", lessonMeta: "Lección 4 · 18 min", restaurant: "En el restaurante", activityName: "Club de conversación", activityDate: "Jueves, 19:00", withTeachers: "Con Natalia y José", announcement: "¡Esta semana practicaremos expresiones colombianas! Trae una frase de tu país para compartir.", file: "Guía de conversación — Unidad 2.pdf", logout: "Salir" },
};

export type Messages = typeof es;

export const messages: Record<Locale, Messages> = {
  es,
  pt: {
    ...es,
    nav: { courses: "Cursos", method: "Método", about: "Sobre nós", members: "Área do aluno", cta: "Quero aprender", menu: "Abrir menu", close: "Fechar menu" },
    hero: { eyebrow: "Espanhol para se conectar de verdade", titleA: "Fale espanhol.", titleB: "Abra o seu mundo.", text: "Aulas online com professores colombianos para brasileiros e americanos que querem conversar com naturalidade, não apenas decorar regras.", primary: "Quero começar", secondary: "Conheça o método", note: "Lista de espera · Sem compromisso", card: "Sua próxima conversa", phrase: "¡Qué gusto conocerte!", translation: "Prazer em conhecer você! · Nice to meet you!", live: "Prática ao vivo", culture: "Cultura colombiana", confidence: "Confiança ao falar" },
    benefits: { eyebrow: "Muito além do vocabulário", title: "Aprenda um idioma. Viva a conexão.", text: "Cada experiência leva o espanhol da aula para a sua vida.", items: [["Conversação prática", "Fale desde a primeira aula com situações que você realmente vai viver."], ["Cultura que se sente", "Descubra expressões, histórias e costumes da Colômbia e da América Latina."], ["Aprendizado flexível", "Combine aulas ao vivo, lições gravadas e prática no seu ritmo."], ["Orientação pessoal", "Receba acompanhamento próximo de professores que entendem seu caminho."]] },
    how: { eyebrow: "Seu caminho, passo a passo", title: "Como funciona a Habla", steps: [["01", "Descobrimos seu ponto de partida", "Conte seus objetivos e encontre a rota ideal para seu nível e rotina."], ["02", "Você aprende fazendo", "Pratique com aulas dinâmicas, desafios curtos e conversas reais."], ["03", "Você se conecta com confiança", "Use seu espanhol para viajar, trabalhar e criar novos vínculos."]] },
    courses: { ...es.courses, eyebrow: "Explore sua próxima etapa", title: "Cursos para o espanhol da vida real", text: "Uma amostra das experiências que estamos preparando.", sample: "Conteúdo de exemplo", level: "Nível", format: "Formato", duration: "Duração", outcome: "Ao final você poderá", cards: [["Primeiras palavras", "A1 · Iniciante", "Ao vivo + gravado", "8 semanas", "Se apresentar, pedir informações e resolver situações cotidianas."], ["Conversas com ritmo", "A2–B1 · Intermediário", "Grupos pequenos", "10 semanas", "Manter conversas espontâneas com mais segurança."], ["Espanhol profissional", "B1–B2 · Avançando", "Workshop ao vivo", "6 semanas", "Comunicar ideias com clareza em reuniões e situações de trabalho."]], cta: "Ver detalhes" },
    founders: { ...es.founders, eyebrow: "Seus professores, seu time", title: "Olá, somos Natalia e José", text1: "Somos professores colombianos e acreditamos que um idioma é aprendido quando deixa de parecer uma prova e começa a parecer uma conversa.", text2: "Criamos a Habla para acompanhar estudantes do Brasil e dos Estados Unidos com um ensino próximo, prático e cheio de cultura.", quote: "Queremos que cada palavra nova aproxime você de uma pessoa, um lugar ou uma possibilidade.", nataliaRole: "Cofundadora · Professora", joseRole: "Cofundador · Professor", placeholder: "Espaço para foto oficial" },
    testimonials: { ...es.testimonials, eyebrow: "Histórias que logo vão falar", title: "A comunidade está começando", text: "Estes espaços mostram como serão apresentadas as experiências reais dos alunos após o lançamento.", placeholder: "DEPOIMENTO DE EXEMPLO — NÃO É UMA AVALIAÇÃO REAL", quotes: ["Aqui contaremos como uma aluna brasileira ganhou confiança para conversar em suas viagens.", "Aqui mostraremos o progresso de um profissional nos Estados Unidos usando espanhol no trabalho.", "Aqui destacaremos uma história real sobre aprender em comunidade e se conectar com a cultura."], student: "Nome do aluno", detail: "País · Curso" },
    final: { eyebrow: "Seu espanhol começa com uma conversa", title: "Pronto para dizer muito mais que olá?", text: "Entre na lista e seja uma das primeiras pessoas a conhecer nossos cursos, datas e benefícios de lançamento.", cta: "Quero participar", note: "Enviaremos apenas novidades importantes." },
    footer: { ...es.footer, text: "Espanhol prático, cultura viva e conexão humana.", explore: "Explore", contact: "Contato", social: "Siga-nos", instagram: "Instagram (em breve)", youtube: "YouTube (em breve)", privacy: "Privacidade", terms: "Termos", rights: "© 2026 Habla. Todos os direitos reservados.", language: "Idioma" },
    login: { title: "Que bom ver você", text: "Continue sua jornada no espanhol.", email: "E-mail", password: "Senha", forgot: "Esqueceu sua senha?", submit: "Entrar no meu espaço", demo: "Protótipo visual: use qualquer e-mail e senha.", back: "Voltar ao início", noAccount: "Ainda não tem acesso?", join: "Entre na lista" },
    members: { ...es.members, eyebrow: "Meu espaço", hello: "Olá, Camila!", text: "Sua próxima conversa está mais perto.", progress: "Progresso do curso", complete: "concluído", continue: "Continuar aula", lessons: "Aulas gravadas", materials: "Materiais", upcoming: "Próximas atividades", announcements: "Avisos dos professores", viewAll: "Ver tudo", download: "Baixar", mock: "Demonstração · Dados de exemplo", lessonName: "Pedir e dar direções", lessonMeta: "Aula 4 · 18 min", restaurant: "No restaurante", activityName: "Clube de conversação", activityDate: "Quinta, 19:00", withTeachers: "Com Natalia e José", announcement: "Nesta semana vamos praticar expressões colombianas! Traga uma frase do seu país para compartilhar.", file: "Guia de conversação — Unidade 2.pdf", logout: "Sair" },
  },
  en: {
    ...es,
    nav: { courses: "Courses", method: "Method", about: "About us", members: "Student area", cta: "Start learning", menu: "Open menu", close: "Close menu" },
    hero: { eyebrow: "Spanish for genuine connection", titleA: "Speak Spanish.", titleB: "Open your world.", text: "Online classes with Colombian teachers for Brazilian and American students who want to speak naturally—not just memorize rules.", primary: "I want to start", secondary: "Explore the method", note: "Waitlist · No commitment", card: "Your next conversation", phrase: "¡Qué gusto conocerte!", translation: "Prazer em conhecer você! · Nice to meet you!", live: "Live practice", culture: "Colombian culture", confidence: "Speaking confidence" },
    benefits: { eyebrow: "Much more than vocabulary", title: "Learn a language. Live the connection.", text: "Every experience is designed to take Spanish from the classroom into your life.", items: [["Practical conversation", "Speak from your first class through situations you will actually experience."], ["Culture you can feel", "Discover expressions, stories, and customs from Colombia and Latin America."], ["Flexible learning", "Combine live classes, recorded lessons, and practice at your own pace."], ["Personal guidance", "Get thoughtful support from teachers who understand your journey."]] },
    how: { eyebrow: "Your path, step by step", title: "How Habla works", steps: [["01", "We find your starting point", "Tell us your goals and find the right path for your level and routine."], ["02", "You learn by doing", "Practice through dynamic classes, short challenges, and real conversations."], ["03", "You connect with confidence", "Use Spanish to travel, work, and build new relationships."]] },
    courses: { ...es.courses, eyebrow: "Explore your next step", title: "Courses for real-life Spanish", text: "A preview of the learning experiences we are creating.", sample: "Sample content", level: "Level", format: "Format", duration: "Duration", outcome: "By the end, you can", cards: [["First words", "A1 · Beginner", "Live + recorded", "8 weeks", "Introduce yourself, ask for information, and navigate everyday situations."], ["Conversations with flow", "A2–B1 · Intermediate", "Small groups", "10 weeks", "Hold spontaneous conversations with greater confidence."], ["Professional Spanish", "B1–B2 · Progressing", "Live workshop", "6 weeks", "Communicate ideas clearly in meetings and professional settings."]], cta: "View details" },
    founders: { ...es.founders, eyebrow: "Your teachers, your team", title: "Hi, we’re Natalia and José", text1: "We’re Colombian teachers who believe a language is learned when it stops feeling like a test and starts feeling like a conversation.", text2: "We created Habla to guide students in Brazil and the United States through personal, practical teaching rich in culture.", quote: "We want every new word to bring you closer to a person, a place, or a possibility.", nataliaRole: "Co-founder · Teacher", joseRole: "Co-founder · Teacher", placeholder: "Official photo placeholder" },
    testimonials: { ...es.testimonials, eyebrow: "Stories that will soon speak", title: "The community is just beginning", text: "These spaces show how real student experiences will be presented after launch.", placeholder: "SAMPLE TESTIMONIAL — NOT A REAL REVIEW", quotes: ["Here we’ll share how a Brazilian student gained the confidence to speak on her travels.", "Here we’ll show the progress of a US professional using Spanish at work.", "Here we’ll feature a real story about learning in community and connecting with culture."], student: "Student name", detail: "Country · Course" },
    final: { eyebrow: "Your Spanish starts with a conversation", title: "Ready to say much more than hello?", text: "Join the list and be among the first to learn about our courses, dates, and launch benefits.", cta: "Join the list", note: "We’ll only send important updates." },
    footer: { ...es.footer, text: "Practical Spanish, living culture, and human connection.", explore: "Explore", contact: "Contact", social: "Follow us", instagram: "Instagram (coming soon)", youtube: "YouTube (coming soon)", privacy: "Privacy", terms: "Terms", rights: "© 2026 Habla. All rights reserved.", language: "Language" },
    login: { title: "Great to see you", text: "Continue your Spanish journey.", email: "Email address", password: "Password", forgot: "Forgot your password?", submit: "Enter my space", demo: "Visual prototype: use any email and password.", back: "Back to home", noAccount: "Don’t have access yet?", join: "Join the list" },
    members: { ...es.members, eyebrow: "My space", hello: "Hi, Camila!", text: "Your next conversation is closer.", progress: "Course progress", complete: "complete", continue: "Continue lesson", lessons: "Recorded lessons", materials: "Materials", upcoming: "Upcoming activities", announcements: "Teacher announcements", viewAll: "View all", download: "Download", mock: "Demo view · Sample data", lessonName: "Asking for and giving directions", lessonMeta: "Lesson 4 · 18 min", restaurant: "At the restaurant", activityName: "Conversation club", activityDate: "Thursday, 7:00 PM", withTeachers: "With Natalia and José", announcement: "This week we’ll practice Colombian expressions! Bring a phrase from your country to share.", file: "Conversation guide — Unit 2.pdf", logout: "Log out" },
  },
};
